apiVersion: v1
clusters:
- cluster:
  certificate-authority: /Users/ajayabd17/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Wed, 22 Oct 2025 21:43:30 IST
        provider: minikube.sigs.k8s.io
        version: v1.36.0
      name: cluster_info
    server: https://127.0.0.1:51432
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Wed, 22 Oct 2025 21:43:30 IST
        provider: minikube.sigs.k8s.io
        version: v1.36.0
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
  client-certificate: /Users/ajayabd17/.minikube/profiles/minikube/client.crt
  client-key: /Users/ajayabd17/.minikube/profiles/minikube/client.key
